/// Portal API calls triggered by deep-links and the Enrollment tab.
///
/// # Deep-link URL format
///
/// The FleetShell portal encodes the action payload as a base64url (no padding)
/// JSON object and constructs a URL of the form:
///
///   fleetshell://<base64url-json>
///
/// Example (before encoding):
///   { "type": "enroll", "payload": "a1b2c3d4", "token": "<jwt>" }
///
/// The client decodes the host portion of the URL and dispatches on `type`.
///
/// # Authentication
///
/// Every deep-link carries a short-lived JWT in the `token` field, issued and
/// signed by the portal (HS256).  The client forwards it verbatim as an HTTP
/// Bearer token wherever required.  The portal verifies its own signature, the
/// `exp` claim, and that `sub` equals the action ID — binding each token to
/// exactly one request.  The client never validates the JWT itself.
///
/// # Enrollment sequence (type = "enroll")
///
/// 1. Persist the client ID from the payload into [`crate::config::AppConfig`].
/// 2. POST probe (`version`, `arch`) to `/api/client/probe/<id>` — signals that
///    the client is reachable and identifies its platform.
/// 3. POST placeholder CSR to `/api/cert/request` — the portal sets the cert
///    status to `"pending"` and begins the issuance flow.
/// 4. Poll `GET /api/cert/status?id=<id>` until the status is `"ready"`.
/// 5. Fetch the certificate from `GET /api/cert/get?id=<id>`.
/// 6. If no private key is stored for this ID, fetch it from
///    `GET /api/cert/key?id=<id>` and persist it as `<id>.key`.
/// 7. POST confirmation to `/api/cert/confirm` — the portal marks the client as
///    fully enrolled.

use serde::{Deserialize, Serialize};
use tauri::Manager as _;  // for AppHandle::state()

// ── Deep-link payload types ───────────────────────────────────────────────────

/// Top-level envelope decoded from the base64url data in a `fleetshell://` URL.
///
/// The `type` field is used as a serde tag so each variant carries its own
/// fields directly.
#[derive(Debug, Deserialize)]
#[serde(tag = "type", rename_all = "lowercase")]
pub enum DeepLinkPayload {
	/// Full enrollment flow initiated from the portal.
	Enroll {
		/// Opaque ID generated by the portal for this enrollment session.
		/// Also the `sub` claim in `token`, binding the JWT to this request.
		payload: String,
		/// Short-lived Bearer JWT issued by the portal.
		/// Forwarded verbatim in `Authorization: Bearer <token>` headers.
		token: Option<String>,
	},
}

// ── Request / response body types ────────────────────────────────────────────

/// Body POSTed to `POST /api/client/probe/<id>`.
#[derive(Debug, Serialize)]
struct ProbeBody {
	/// Semver version string from Cargo.toml, e.g. "0.1.0".
	version: &'static str,
	/// Target CPU architecture string, e.g. "x86_64", "aarch64".
	arch: &'static str,
}

/// Body POSTed to `POST /api/cert/request`.
#[derive(Debug, Serialize)]
struct CertRequestBody {
	id:  String,
	/// Placeholder — a real PKCS#10 CSR (PEM) will replace this in Phase 2.
	csr: String,
}

/// Body POSTed to `POST /api/cert/confirm`.
#[derive(Debug, Serialize)]
struct CertConfirmBody {
	id: String,
}

/// Response from `GET /api/cert/status?id=<id>`.
#[derive(Debug, Deserialize)]
struct CertStatusResponse {
	/// `"none"` | `"pending"` | `"ready"`
	status: String,
}

/// Response from `GET /api/cert/get?id=<id>`.
#[derive(Debug, Deserialize)]
struct CertGetResponse {
	cert: String,
}

/// Response from `GET /api/cert/key?id=<id>`.
#[derive(Debug, Deserialize)]
struct KeyGetResponse {
	key: String,
}

// ── Public entry points ───────────────────────────────────────────────────────

/// Decode and dispatch a `fleetshell://` deep-link URL.
///
/// Extracts the base64url payload, parses it, and calls the appropriate handler.
///
/// On **success** the window is left wherever it is — the user is watching the
/// portal page and an uninvited pop-up is disruptive.
///
/// On **failure** the logging tab is surfaced so the user can read the error.
pub async fn handle_deep_link(app: &tauri::AppHandle, url: url::Url) {
	log::info!("Handling deep link: {}", url);

	let result = dispatch(app, &url).await;
	match result {
		Ok(msg) => {
			// Enrollment completed — stay out of the user's way.
			log::info!("Deep link handled successfully: {}", msg);
		}
		Err(e) => {
			// Surface the logging tab so the user can see what went wrong.
			log::error!("Deep link error: {}", e);
			crate::util::navigate(app, "logging");
		}
	}
}

// ── Internal dispatcher ───────────────────────────────────────────────────────

async fn dispatch(app: &tauri::AppHandle, url: &url::Url) -> Result<String, String> {
	let payload = decode_url_payload(url)?;

	match payload {
		DeepLinkPayload::Enroll { payload: id, token } => {
			let cfg = crate::config::load(app);
			handle_enroll(app, &cfg.portal_base_url, &id, token.as_deref()).await
		}
	}
}

// ── Enrollment orchestrator ───────────────────────────────────────────────────

/// Runs all six enrollment steps in sequence.
///
/// Each step is logged individually so the user can follow progress in the
/// Logging tab.  The function returns a short summary string on success or a
/// human-readable error string on the first failure.
async fn handle_enroll(
	app:      &tauri::AppHandle,
	base_url: &str,
	id:       &str,
	token:    Option<&str>,
) -> Result<String, String> {
	let base = base_url.trim_end_matches('/');

	// ── Step 1: persist the client ID ────────────────────────────────────────
	let mut cfg = crate::config::load(app);

	// Archive files belonging to the previous identity (if different from the
	// incoming one) so old certs don't linger alongside the new ones.
	if let Some(ref old_id) = cfg.client_id.clone() {
		if old_id != id {
			log::info!("Enrollment: retiring old client ID {old_id}");
			crate::config::archive_identity(app, old_id);
		}
	}
	// Also archive any files already on disk for the incoming ID — covers
	// re-enrollment with the same ID (e.g. cert expiry).
	crate::config::archive_identity(app, id);

	cfg.client_id = Some(id.to_string());
	if let Err(e) = crate::config::save(app, &cfg) {
		log::warn!("Could not persist client ID: {e}");
	}
	log::info!("Enrollment [1/7]: client ID = {id}");

	// ── Step 2: probe ────────────────────────────────────────────────────────
	send_probe(base, id, token).await?;
	log::info!("Enrollment [2/7]: probe sent");

	// ── Step 3: submit placeholder CSR ───────────────────────────────────────
	submit_csr(base, id, token).await?;
	log::info!("Enrollment [3/7]: CSR submitted");

	// ── Steps 4+5: poll until cert is ready, then fetch ──────────────────────
	let cert = poll_and_fetch_cert(base, id).await?;
	if let Err(e) = crate::config::save_cert(app, id, &cert) {
		// Non-fatal: log the failure but continue — the cert is still in memory
		// and the confirm step should still fire so the portal knows we got it.
		log::warn!("Could not persist certificate to disk: {e}");
	}
	log::info!("Enrollment [4+5/7]: cert received and persisted ({} bytes)", cert.len());

	// ── Step 6: fetch private key if not already on disk ─────────────────────
	//
	// While we send a placeholder CSR, the portal generates the keypair on its
	// side and hands the private key back to us here.  In Phase 2 the client
	// will generate its own keypair and this step will be skipped entirely.
	if crate::config::has_key(app, id) {
		log::info!("Enrollment [6/7]: private key already on disk — skipping fetch");
	} else {
		let key = fetch_key(base, id, token).await?;
		if let Err(e) = crate::config::save_key(app, id, &key) {
			// Non-fatal for the same reason as save_cert above.
			log::warn!("Could not persist private key to disk: {e}");
		} else {
			log::info!("Enrollment [6/7]: private key received and persisted ({} bytes)", key.len());
		}
	}

	// ── Step 7: confirm receipt ───────────────────────────────────────────────
	confirm_cert(base, id, token).await?;
	log::info!("Enrollment [7/7]: confirmed");

	// ── Hot-reload TLS ────────────────────────────────────────────────────────────────────────────
	// Now that the cert and key are on disk, promote the API server from plain
	// HTTP to HTTPS without requiring a restart.  Any subsequent connection
	// (including the portal's Connect form) will benefit immediately.
	if let (Some(cert_pem), Some(key_pem)) = (
		crate::config::load_cert(app, id),
		crate::config::load_key(app, id),
	) {
		match crate::server::build_tls_acceptor(&cert_pem, &key_pem) {
			Ok(acceptor) => {
				let tls = app.state::<crate::server::TlsState>();
				*tls.0.write().await = Some(acceptor);
				log::info!("Enrollment: API server promoted to HTTPS (id={id})");
			}
			Err(e) => log::warn!(
				"Enrollment: TLS hot-reload failed ({e}); restart to activate HTTPS"
			),
		}
	}

	Ok(format!(
		"Enrollment complete — id={id}, cert {} bytes",
		cert.len()
	))
}

// ── Step helpers ──────────────────────────────────────────────────────────────

/// Build a shared [`reqwest::Client`] for all portal calls.
fn build_client() -> Result<reqwest::Client, String> {
	reqwest::Client::builder()
		.build()
		.map_err(|e| format!("HTTP client error: {e}"))
}

/// POST `{version, arch}` to `<base>/api/client/probe/<id>`.
async fn send_probe(base: &str, id: &str, token: Option<&str>) -> Result<(), String> {
	let url = format!("{base}/api/client/probe/{id}");
	log::info!("Probe: POST {url}");

	let client = build_client()?;
	let body = ProbeBody {
		version: env!("CARGO_PKG_VERSION"),
		arch:    std::env::consts::ARCH,
	};

	let mut req = client.post(&url).json(&body);
	if let Some(t) = token {
		req = req.bearer_auth(t);
	}

	let resp   = req.send().await.map_err(|e| format!("Probe request failed: {e}"))?;
	let status = resp.status();
	let text   = resp.text().await.unwrap_or_default();

	if !status.is_success() {
		return Err(format!("Probe: HTTP {status}\n{text}"));
	}

	log::info!("Probe: HTTP {status}");
	Ok(())
}

/// POST placeholder CSR to `<base>/api/cert/request`.
async fn submit_csr(base: &str, id: &str, token: Option<&str>) -> Result<(), String> {
	let url = format!("{base}/api/cert/request");
	log::info!("Cert request: POST {url}");

	let client = build_client()?;
	let body = CertRequestBody {
		id:  id.to_string(),
		csr: "placeholder-csr-not-a-real-csr".to_string(),
	};

	let mut req = client.post(&url).json(&body);
	if let Some(t) = token {
		req = req.bearer_auth(t);
	}

	let resp   = req.send().await.map_err(|e| format!("Cert request failed: {e}"))?;
	let status = resp.status();

	if !status.is_success() {
		let text = resp.text().await.unwrap_or_default();
		return Err(format!("Cert request: HTTP {status}\n{text}"));
	}

	log::info!("Cert request: HTTP {status}");
	Ok(())
}

/// Poll `GET <base>/api/cert/status?id=<id>` until the status is `"ready"`,
/// then fetch and return the certificate from `GET <base>/api/cert/get?id=<id>`.
///
/// Polls every 3 seconds for up to 120 seconds before giving up.
async fn poll_and_fetch_cert(base: &str, id: &str) -> Result<String, String> {
	const POLL_INTERVAL: std::time::Duration = std::time::Duration::from_secs(3);
	const TIMEOUT:       std::time::Duration = std::time::Duration::from_secs(120);

	let client     = build_client()?;
	let status_url = format!("{base}/api/cert/status");
	let start      = std::time::Instant::now();

	log::info!(
		"Cert status: polling GET {status_url}?id={id} every {}s (timeout {}s)",
		POLL_INTERVAL.as_secs(),
		TIMEOUT.as_secs(),
	);

	loop {
		if start.elapsed() >= TIMEOUT {
			return Err(format!(
				"Cert status polling timed out after {}s",
				TIMEOUT.as_secs()
			));
		}

		let resp = client
			.get(&status_url)
			.query(&[("id", id)])
			.send()
			.await
			.map_err(|e| format!("Cert status poll failed: {e}"))?;

		let http_status = resp.status();
		if !http_status.is_success() {
			let text = resp.text().await.unwrap_or_default();
			return Err(format!("Cert status: HTTP {http_status}\n{text}"));
		}

		let body: CertStatusResponse = resp
			.json()
			.await
			.map_err(|e| format!("Cert status JSON parse failed: {e}"))?;

		log::debug!("Cert status for {id}: {}", body.status);

		match body.status.as_str() {
			"ready" => break,
			"pending" => {
				tokio::time::sleep(POLL_INTERVAL).await;
			}
			"none" => {
				return Err(format!(
					"Cert status for {id} is 'none' — enrollment session \
					 may have expired or been invalidated; restart enrollment"
				));
			}
			other => {
				return Err(format!("Unexpected cert status: '{other}'"));
			}
		}
	}

	// Fetch the certificate now that it is ready.
	let get_url = format!("{base}/api/cert/get");
	log::info!("Cert fetch: GET {get_url}?id={id}");
	let resp = client
		.get(&get_url)
		.query(&[("id", id)])
		.send()
		.await
		.map_err(|e| format!("Cert fetch failed: {e}"))?;

	let http_status = resp.status();
	if !http_status.is_success() {
		let text = resp.text().await.unwrap_or_default();
		return Err(format!("Cert fetch: HTTP {http_status}\n{text}"));
	}

	let body: CertGetResponse = resp
		.json()
		.await
		.map_err(|e| format!("Cert fetch JSON parse failed: {e}"))?;

	log::info!("Certificate received: {} bytes", body.cert.len());
	Ok(body.cert)
}

/// Fetch the private key from `GET <base>/api/cert/key?id=<id>`.
///
/// The portal generates the keypair while we still send a placeholder CSR.
/// In Phase 2, when the client generates its own keypair, this call is
/// bypassed entirely (the key is already on disk from generation time).
async fn fetch_key(base: &str, id: &str, token: Option<&str>) -> Result<String, String> {
	let url = format!("{base}/api/cert/key");
	log::info!("Key fetch: GET {url}?id={id}");

	let client = build_client()?;
	let mut req = client.get(&url).query(&[("id", id)]);
	if let Some(t) = token {
		req = req.bearer_auth(t);
	}

	let resp        = req.send().await.map_err(|e| format!("Key fetch failed: {e}"))?;
	let http_status = resp.status();
	if !http_status.is_success() {
		let text = resp.text().await.unwrap_or_default();
		return Err(format!("Key fetch: HTTP {http_status}\n{text}"));
	}

	let body: KeyGetResponse = resp
		.json()
		.await
		.map_err(|e| format!("Key fetch JSON parse failed: {e}"))?;

	log::info!("Private key received: {} bytes", body.key.len());
	Ok(body.key)
}

/// POST `{id}` to `<base>/api/cert/confirm` — signals that the client has
/// received and stored the certificate.
async fn confirm_cert(base: &str, id: &str, token: Option<&str>) -> Result<(), String> {
	let url = format!("{base}/api/cert/confirm");
	log::info!("Cert confirm: POST {url}");

	let client = build_client()?;
	let body   = CertConfirmBody { id: id.to_string() };

	let mut req = client.post(&url).json(&body);
	if let Some(t) = token {
		req = req.bearer_auth(t);
	}

	let resp   = req.send().await.map_err(|e| format!("Cert confirm failed: {e}"))?;
	let status = resp.status();

	if !status.is_success() {
		let text = resp.text().await.unwrap_or_default();
		return Err(format!("Cert confirm: HTTP {status}\n{text}"));
	}

	log::info!("Cert confirm: HTTP {status}");
	Ok(())
}

// ── URL decoder ───────────────────────────────────────────────────────────────

/// Extract and decode the base64url JSON envelope from a `fleetshell://` URL.
///
/// The portal places the payload in the *host* position of the URL:
///
///   fleetshell://<base64url-json>
///
/// `url::Url` returns the host as a plain string which we decode directly.
fn decode_url_payload(url: &url::Url) -> Result<DeepLinkPayload, String> {
	let raw = url
		.host_str()
		.map(|s| s.to_owned())
		.unwrap_or_else(|| {
			url.as_str()
				.strip_prefix("fleetshell://")
				.unwrap_or("")
				.trim_start_matches('/')
				.to_owned()
		});

	if raw.is_empty() {
		return Err("Deep-link URL carried no payload".to_string());
	}

	use base64::Engine as _;
	let bytes = base64::engine::general_purpose::URL_SAFE_NO_PAD
		.decode(raw.as_bytes())
		.map_err(|e| format!("Base64 decode failed: {e}"))?;

	serde_json::from_slice::<DeepLinkPayload>(&bytes)
		.map_err(|e| format!("Payload JSON parse failed: {e}"))
}
