/// Portal API calls triggered by deep-links and the Enrollment tab.
///
/// # Deep-link URL format
///
/// The FleetShell portal encodes the action payload as a base64url (no padding)
/// JSON object and constructs a URL of the form:
///
///   fleetshell://<base64url-json>
///
/// Example (before encoding):
///   { "type": "probe", "payload": "a1b2c3d4", "token": "<jwt>" }
///
/// The client decodes the host portion of the URL and dispatches on `type`.
///
/// # Authentication
///
/// Every deep-link carries a short-lived JWT in the `token` field, issued and
/// signed by the portal (RS256 / ES256).  The client forwards it verbatim as an
/// HTTP Bearer token.  The portal verifies its own signature, the `exp` claim,
/// and that `sub` equals the action ID — binding each token to exactly one
/// request.  The client does not need to validate the JWT itself; validation
/// lives entirely on the portal side.

use serde::{Deserialize, Serialize};

// ── Deep-link payload types ───────────────────────────────────────────────────

/// Top-level envelope decoded from the base64url data in a `fleetshell://` URL.
///
/// The `type` field is used as a serde tag so each variant carries its own
/// fields directly.
#[derive(Debug, Deserialize)]
#[serde(tag = "type", rename_all = "lowercase")]
pub enum DeepLinkPayload {
    /// Connectivity / registration probe initiated from the portal.
    Probe {
        /// Opaque ID generated by the portal for this probe session.
        /// It also appears as the `sub` claim in `token`, binding the JWT to
        /// this specific request.
        payload: String,
        /// Short-lived Bearer JWT issued by the portal.
        /// The client forwards it as `Authorization: Bearer <token>` without
        /// attempting to validate the signature locally.
        token: Option<String>,
    },
}

// ── Probe request / response ──────────────────────────────────────────────────

/// Body POSTed to `POST /api/client/probe/<id>`.
#[derive(Debug, Serialize)]
struct ProbeBody {
    /// Semver version string from Cargo.toml, e.g. "0.1.0".
    version: &'static str,
    /// Target CPU architecture string, e.g. "x86_64", "aarch64".
    arch: &'static str,
}

// ── Public entry points ───────────────────────────────────────────────────────

/// Decode and dispatch a `fleetshell://` deep-link URL.
///
/// Extracts the base64url payload from the URL, parses it, and calls the
/// appropriate handler.  On any error or completion the logging tab is shown
/// in the UI so the user can see what happened.
pub async fn handle_deep_link(app: &tauri::AppHandle, url: url::Url) {
    log::info!("Handling deep link: {}", url);

    let result = dispatch(app, &url).await;
    match result {
        Ok(msg) => {
            log::info!("Deep link handled: {}", msg);
            crate::util::navigate(app, "logging");
        }
        Err(e) => {
            log::error!("Deep link error: {}", e);
            crate::util::navigate(app, "logging");
        }
    }
}

// ── Internal helpers ──────────────────────────────────────────────────────────

async fn dispatch(app: &tauri::AppHandle, url: &url::Url) -> Result<String, String> {
    let payload = decode_url_payload(url)?;

    match payload {
        DeepLinkPayload::Probe { payload: id, token } => {
            let cfg = crate::config::load(app);
            send_probe(&cfg.portal_base_url, &id, token.as_deref()).await
        }
    }
}

/// Extract the base64url-encoded JSON from the URL.
///
/// The portal encodes the payload as base64url (no-padding) and places it in
/// the host position of the URL:
///
///   fleetshell://<base64url-json>
///
/// `url::Url` returns the host as a string which we can decode directly.
fn decode_url_payload(url: &url::Url) -> Result<DeepLinkPayload, String> {
    // Prefer the host string; fall back to stripping the scheme manually so
    // unusual URL serialisations (e.g. path-only) are also handled.
    let raw = url
        .host_str()
        .map(|s| s.to_owned())
        .unwrap_or_else(|| {
            url.as_str()
                .strip_prefix("fleetshell://")
                .unwrap_or("")
                .trim_start_matches('/')
                .to_owned()
        });

    if raw.is_empty() {
        return Err("Deep-link URL carried no payload".to_string());
    }

    use base64::Engine as _;
    let bytes = base64::engine::general_purpose::URL_SAFE_NO_PAD
        .decode(raw.as_bytes())
        .map_err(|e| format!("Base64 decode failed: {e}"))?;

    serde_json::from_slice::<DeepLinkPayload>(&bytes)
        .map_err(|e| format!("Payload JSON parse failed: {e}"))
}

/// POST version + arch to `<base_url>/api/client/probe/<id>`.
///
/// If a Bearer token is present it is forwarded as-is in the Authorization
/// header.  The portal is responsible for validating the JWT.
async fn send_probe(
    base_url: &str,
    id: &str,
    token: Option<&str>,
) -> Result<String, String> {
    let url = format!(
        "{}/api/client/probe/{}",
        base_url.trim_end_matches('/'),
        id,
    );
    log::info!("Probe: POST {}", url);

    let client = reqwest::Client::builder()
        .build()
        .map_err(|e| format!("HTTP client error: {e}"))?;

    let body = ProbeBody {
        version: env!("CARGO_PKG_VERSION"),
        arch:    std::env::consts::ARCH,
    };

    let mut req = client.post(&url).json(&body);
    if let Some(t) = token {
        req = req.bearer_auth(t);
    }

    let response = req
        .send()
        .await
        .map_err(|e| format!("Probe request failed: {e}"))?;

    let status = response.status();
    let text = response
        .text()
        .await
        .map_err(|e| format!("Failed to read probe response: {e}"))?;

    log::info!("Probe: response {} ({} bytes)", status, text.len());
    Ok(format!("Probe → HTTP {status}\n\n{text}"))
}
