// seed_login_accounts.mjs -- dev login accounts + persona labels for the
// identity model (see docs/portal_ui.md). Run AFTER seed_test_users.py (which
// creates the 6 test personas) and AFTER migrate_identity_local.sql.
//
// It EMITS idempotent SQL to stdout (no DB driver dependency -- only node:crypto
// for scrypt hashing, which cannot be done in plain SQL). Pipe it to psql:
//
//   node infrastructure/import/seed_login_accounts.mjs | psql "$LOCAL_WRITER_URL"
//   # or:  node infrastructure/import/seed_login_accounts.mjs > seed.sql
//   #      psql "$LOCAL_WRITER_URL" -f seed.sql
//
// It:
//   * sets role_label + is_admin on the 6 test personas,
//   * creates two login_accounts and links their identities:
//       super / super123  -> all 6 personas (demo the identity selector),
//       nora  / nora123    -> Nora only     (single-persona: no selector).
//
// Password hashing mirrors src/lib/server/password.ts EXACTLY (scrypt format);
// keep the two in sync.

import { scrypt, randomBytes } from 'node:crypto';
import { promisify } from 'node:util';

const scryptAsync = promisify(scrypt);
const N = 16384,
	R = 8,
	P = 1,
	KEYLEN = 32;

async function hashPassword(password) {
	const salt = randomBytes(16);
	const key = await scryptAsync(password, salt, KEYLEN, { N, r: R, p: P });
	return `scrypt$${N}$${R}$${P}$${salt.toString('hex')}$${key.toString('hex')}`;
}

// Test personas (fixed ids from seed_test_users.py) -> (role_label, is_admin).
const PERSONAS = [
	['dddd0000-0000-0000-0000-000000000001', 'SystemAdmin', true],
	['dddd0000-0000-0000-0000-000000000002', 'Service Engineer', false],
	['dddd0000-0000-0000-0000-000000000003', 'User', false],
	['dddd0000-0000-0000-0000-000000000004', 'RSC Operator', false],
	['dddd0000-0000-0000-0000-000000000005', 'BURepresentative', false],
	['dddd0000-0000-0000-0000-000000000006', 'Helpdesk', false]
];

// account username, email, password, [linked persona ids]
const ACCOUNTS = [
	['super', 'super@test.local', 'super,user,113', PERSONAS.map((p) => p[0])],
	[
		'nora',
		'nora@test.local',
		'nora,secret,113',
		['dddd0000-0000-0000-0000-000000000003']
	],
	[
		'fabian',
		'fabian@test.local',
		'Bamboozled66',
		[
			'dddd0000-0000-0000-0000-000000000003',
			'dddd0000-0000-0000-0000-000000000001'
		]
	],
	[
		'marcus',
		'marcus@test.local',
		'Wandering66',
		[
			'dddd0000-0000-0000-0000-000000000003',
			'dddd0000-0000-0000-0000-000000000001'
		]
	],
	[
		'cornelia',
		'cornelia@test.local',
		'Frolicking66',
		[
			'dddd0000-0000-0000-0000-000000000003',
			'dddd0000-0000-0000-0000-000000000001'
		]
	],
	[
		'tobias',
		'tobias@test.local',
		'Meandering66',
		[
			'dddd0000-0000-0000-0000-000000000003',
			'dddd0000-0000-0000-0000-000000000001'
		]
	],
	[
		'steve',
		'steve@test.local',
		'Tenacious66',
		[
			'dddd0000-0000-0000-0000-000000000003',
			'dddd0000-0000-0000-0000-000000000001'
		]
	],
	[
		'marcell',
		'marcell@test.local',
		'Confounded66',
		[
			'dddd0000-0000-0000-0000-000000000003',
			'dddd0000-0000-0000-0000-000000000001'
		]
	],
	[
		'hermann',
		'hermann@test.local',
		'Bedraggled66',
		[
			'dddd0000-0000-0000-0000-000000000003',
			'dddd0000-0000-0000-0000-000000000001'
		]
	],
	[
		'sergej',
		'sergej@test.local',
		'Prancing66',
		[
			'dddd0000-0000-0000-0000-000000000003',
			'dddd0000-0000-0000-0000-000000000001'
		]
	],
	[
		'klaus',
		'klaus@test.local',
		'Prowling66',
		[
			'dddd0000-0000-0000-0000-000000000003',
			'dddd0000-0000-0000-0000-000000000001'
		]
	],
	[
		'daniel',
		'daniel@test.local',
		'Skulking66',
		[
			'dddd0000-0000-0000-0000-000000000003',
			'dddd0000-0000-0000-0000-000000000001'
		]
	],
	[
		'goeksal',
		'goeksal@test.local',
		'Ambling66',
		[
			'dddd0000-0000-0000-0000-000000000003',
			'dddd0000-0000-0000-0000-000000000001'
		]
	],
	[
		'sascha',
		'sascha@test.local',
		'Bamboozled66',
		[
			'dddd0000-0000-0000-0000-000000000003',
			'dddd0000-0000-0000-0000-000000000001'
		]
	],
	[
		'hendrik',
		'hendrik@test.local',
		'Belligerent66',
		[
			'dddd0000-0000-0000-0000-000000000003',
			'dddd0000-0000-0000-0000-000000000001'
		]
	],
	[
		'carsten',
		'carsten@test.local',
		'Lollygagging66',
		[
			'dddd0000-0000-0000-0000-000000000003',
			'dddd0000-0000-0000-0000-000000000001'
		]
	],
	[
		'matthias',
		'matthias@test.local',
		'Traipsing66',
		[
			'dddd0000-0000-0000-0000-000000000003',
			'dddd0000-0000-0000-0000-000000000001'
		]
	],
	[
		'lisa',
		'lisa@test.local',
		'Perturbed',
		[
			'dddd0000-0000-0000-0000-000000000003',
			'dddd0000-0000-0000-0000-000000000001'
		]
	]
];

// Single-quote escaping for SQL string literals (our values have none, but be safe).
const q = (s) => `'${String(s).replace(/'/g, "''")}'`;

const out = [];
out.push(
	'-- Generated by seed_login_accounts.mjs. Idempotent. Apply to the LOCAL plane.'
);
out.push('BEGIN;');

for (const [uid, label, isAdmin] of PERSONAS) {
	out.push(
		`UPDATE app_user SET role_label = ${q(label)}, is_admin = ${isAdmin} WHERE user_id = ${q(uid)};`
	);
}

for (const [username, email, password, personaIds] of ACCOUNTS) {
	const hash = await hashPassword(password);
	out.push(
		`INSERT INTO login_account (account_id, username, email, password_hash, display_name)\n` +
			`VALUES ('acct:' || nextval('login_account_seq'), ${q(username)}, ${q(email)}, ${q(hash)}, ${q(username)})\n` +
			`ON CONFLICT (username) DO UPDATE SET password_hash = EXCLUDED.password_hash, email = EXCLUDED.email;`
	);
	for (let i = 0; i < personaIds.length; i++) {
		const uid = personaIds[i];
		const isPrimary = i === 0; // first linked persona = the account's default identity
		// JOIN app_user so a persona that seed_test_users.py did not create (it only
		// makes a persona per group it finds) is silently skipped, not an FK error.
		out.push(
			`INSERT INTO account_persona (account_id, user_id, is_primary)\n` +
				`SELECT la.account_id, u.user_id, ${isPrimary} FROM login_account la\n` +
				`JOIN app_user u ON u.user_id = ${q(uid)}\n` +
				`WHERE la.username = ${q(username)}\n` +
				`ON CONFLICT (account_id, user_id) DO UPDATE SET is_primary = EXCLUDED.is_primary;`
		);
	}
}

out.push('COMMIT;');
// Credentials reminder to stderr so it does not pollute the SQL on stdout.
console.error(
	'Seed SQL written to stdout. Logins: super/super123 (all personas, SuperUser=admin), nora/nora123.'
);
process.stdout.write(out.join('\n') + '\n');
